---
title: "Group Project"
author: "Ed Lawrence"
date: "2024-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(ggplot2)

CODMAPS <- read.csv("CODMaps.csv")
CODGameModes <- read.csv("CODGameModes.csv")
CODGames_p1_380 <- read.csv("CODGames_p1_380.csv")
CODGames_p2_380 <- read.csv("CODGames_p2_380.csv")
```

## Task 1

```{r}

# Step 1: Combine p1 and p2

CODGames_P1andP2 <- full_join(CODGames_p1_380, CODGames_p2_380)

# Step 2: Select only columns relevant to task 1 research question

CODGames_P1andP2 <- CODGames_P1andP2 %>%
  select(Map1, Map2, Choice, MapVote)

# Step 3: Remove Cases where values are missing

CODGames_P1andP2 <- CODGames_P1andP2 %>%
  filter(Map1 != "")

# Step 4: Convert MapVote into two separate Numeric Columns

CODGames_P1andP2 <- CODGames_P1andP2 %>%
  separate(MapVote, into = c("left", "right"), sep = " to ") %>%
  mutate(
    result_left = as.numeric(left),
    result_right = as.numeric(right)
  )

CODGames_P1andP2$left <- NULL
CODGames_P1andP2$right <- NULL

# Step 5: Check if there was a tie or not in the vote

CODGames_P1andP2 <- CODGames_P1andP2 %>%
  mutate("tie" = ifelse(result_left == result_right, "Yes", "No"))

```
